stages:
  - test
  - build
  - scan
  - deploy

variables:
  DOCKER_DRIVER: overlay2

image: docker:27.3.1 

services: 
  - docker:27.3.1-dind

test:
  stage: test
  image: python:3.9
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest tests/
  only:
    - main

build:
  stage: build
  script:
    - docker build -t myapp:latest .
  only:
    - main

scan:
  stage: scan
  script:
    - docker pull aquasec/trivy
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 1 --severity HIGH,CRITICAL myapp:latest
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker-compose up -d --build
  only:
    - main
