stages:
  - test
  - build
  - scan
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_REPO: hannachiyou/myapp 
  DOCKER_TAG: latest 
  DOCKER_REGISTRY: docker.io

image: docker:27.3.1 

services: 
  - docker:27.3.1-dind

test:
  stage: test
  image: python:3.9
  variables: 
    PYTHONPATH: "${CI_PROJECT_DIR}"
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest # Install pytest
    - pytest tests/
  only:
    - main

build: 
  stage: build 
  script: 
    - docker build -t $DOCKER_REPO:$DOCKER_TAG . 
  only: 
    - main 

push: 
  stage: push 
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY 
    - docker tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REGISTRY/$DOCKER_REPO:$DOCKER_TAG 
    - docker push $DOCKER_REGISTRY/$DOCKER_REPO:$DOCKER_TAG 
  only:
    - main 

scan: 
  stage: scan 
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY
    - docker pull $DOCKER_REGISTRY/$DOCKER_REPO:$DOCKER_TAG 
    - docker pull aquasec/trivy 
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --exit-code 1 --severity HIGH,CRITICAL $DOCKER_REGISTRY/$DOCKER_REPO:$DOCKER_TAG 
  only: - main

deploy:
  stage: deploy
  script:
    - docker-compose up -d --build
  only:
    - main
