version: '3.8'

networks:
  monitoring:

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/CI-CD_Project/article
    networks:
      - monitoring
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/google-containers/cadvisor
    ports:
      - "8080:8080"
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
