version: '3.8'

networks: 
  project: 
    external: true

services:
  web:
    build: 
      context: ./app
    ports:
      - "443:443"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/CI-CD_Project/article
    networks:
      - project
    depends_on:
      - mongo

  mongo:
    build:
      context: ./mongo 
    container_name: mongo-container
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
      - ./mongo/CI-CD_Project.article.json:/docker-entrypoint-initdb.d/CI-CD_Project.article.json
    networks:
      - project

  prometheus:
    image: prom/prometheus
    volumes:
      - /builds/h3hitema8801048/ci-cd/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - project

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - project

  cadvisor:
    image: gcr.io/google-containers/cadvisor
    ports:
      - "8080:8080"
    networks:
      - project
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
