# Use the official Python image as a base image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Define build arguments for the certificates
ARG CERT_PEM
ARG KEY_PEM

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Save the certificates from the build arguments
RUN echo "$CERT_PEM" > /app/cert.pem \
    && echo "$KEY_PEM" > /app/key.pem

# Expose the port the app runs on
EXPOSE 443

# Define the command to run the app
CMD ["python", "app.py"]
