name: CI/CD Pipeline for project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Phase
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python and run tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run Tests
        working-directory: app
        run: |
          python -m unittest discover -s tests

  build & push:
    name: Build Docker Images & Push Them To Docker Hub
    runs-on: ubuntu-latest
    needs: test # Ensures this job runs only if the 'test' job succeeds

    env:
      APP_IMAGE_NAME: myapp
      DB_IMAGE_NAME: mydb

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
       # Step 3: Build Flask App Docker Image
      - name: Build Flask App Image
        run: |
          docker build -t $DOCKER_USERNAME/$APP_IMAGE_NAME:latest app/

      # Step 4: Build MongoDB Docker Image
      - name: Build MongoDB Image
        run: |
          docker build -t $DOCKER_USERNAME/$DB_IMAGE_NAME:latest mongo/

       # Step 5: Push Flask App Docker Image
      - name: Push Flask App Image
        run: |
          docker push $DOCKER_USERNAME/$APP_IMAGE_NAME:latest

      # Step 6: Push MongoDB Docker Image
      - name: Push MongoDB Image
        run: |
          docker push $DOCKER_USERNAME/$DB_IMAGE_NAME:latest

